### ISSUE TITLE
Identifier?

### ISSUE THREAD

**Issue by jestelle** [downie/playlate#1]
Not sure this identifier _needs_ to be here... and even worse, you may really not want it here.
Just FYI
https://github.com/downie/playlate/blob/f1c0495c804781969dbb6af39a8c24fa7ae4aeba/.nova/Tasks/Playdate%20Simulator.json#L7

**Comment by bedinotti** [comment]
That's a good callout. I don't actually know what this identifier is. I'll ask in the forums.

I'm not worried about it being public. This isn't my ID, but one that ships with the Playdate SDK.  You can see for yourself in `PlaydateSDK/Examples/Game Template`.

<img width="701" alt="CleanShot 2022-03-11 at 08 56 48@2x" src="https://user-images.githubusercontent.com/547866/157912478-fe2ef27c-dbc0-4d64-8a28-8954fd6d6fce.png">

**Comment by bedinotti** [comment]
Asked in the forums: https://devforum.play.date/t/whats-the-significance-of-the-uuid-identifier-in-the-nova-folder/3927

**Comment by bedinotti** [comment]
Yup, it's fine. It sounds like it helps Nova disambiguate between multiple tasks in a project. https://devforum.play.date/t/whats-the-significance-of-the-uuid-identifier-in-the-nova-folder/3927/2

Again, thanks for checking. 👍🏻
